mysql:
  host: 127.0.0.1
  port: 3306
  dbname: order
  username: root
  password:
  charset: utf8
  parseTime: True
  loc: Local
  # 10s
  timeout: 10
  # 设置空闲连接池中的最大连接数。
  max-idle-conns: 10
  # 设置到数据库的最大打开连接数
  max-open-conns: 100
  # 设置连接可重用的最大时间
  conn-max-life-time: 24*3600

zap:
  # 是否压缩文件，使用gzip
  compress: 1
  consoleStdout: 1
  fileStdout: 0
  # 日志级别
  level: debug
  # 日志时间戳
  localTime: 1
  # 最长保存天数
  maxAge: 30
  # 最多备份几个
  maxBackups: 300
  # 日志文件大小
  maxSize: 10240
  # 日志文件名
  path: ./logs/order.log

amap:
  # 高德地图key
  key: a8048b58a245ca4328c9cd4c095cc660